name: taney-monitoring

channels:
  - conda-forge

dependencies:
  - python=3.11

   # core stack (no versions)
  - numpy=1.23.5
  - pandas
  - scipy=1.9.3
  - matplotlib
  - netcdf4
  - xarray

  # utilities (optional light pinning ok)
  - openpyxl
  - pyyaml
  - dateparser
  - python-dateutil
  - gsw

  # jupyter stack
  - notebook
  - ipympl

  - pip
  - pip:
      - envass==1.0.0
      - cmocean==3.0.3
      - pyRSKtools==1.1.1
      - numpy==1.23.5 # Required to avoid pip to upgrade
      - scipy==1.9.3 # Required to avoid pip to upgrade

